# Generated by Django 5.2.5 on 2025-08-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
